# Runtime
DEBUG = False
MAX_STEPS = 10e5
MAX_GAME_LENGTH = 10e5
CONTROL_STATE = 81

# Agents
PLAYER_INIT_X = 2
PLAYER_INIT_Y = 0
PLAYER_INIT_POSS = False
PLAYER_NAME = 'A'
PLAYER_INFO = (PLAYER_INIT_X, PLAYER_INIT_Y, PLAYER_INIT_POSS, PLAYER_NAME)

OPPONENT_INIT_X = 1
OPPONENT_INIT_Y = 0
OPPONENT_INIT_POSS = True
OPPONENT_NAME = 'B'
OPPONENT_INFO = (OPPONENT_INIT_X, OPPONENT_INIT_Y, OPPONENT_INIT_POSS, OPPONENT_NAME)

# Environment
FIELD_DIM_X = 4
FIELD_DIM_Y = 2

NUM_STATES = 128
NUM_ACTIONS = 5

# Actions
NORTH = 0
SOUTH = 1
WEST = 2
EAST = 3
STICK = 4
